export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SET_CURRENT_ID = 'SET_CURRENT_ID';
export const HANDLE_INPUT_CHANGE = 'HANDLE_INPUT_CHANGE';
export const CHANGE_WARNING = 'CHANGE_EMPTY_VALUE';
export const ADD_NEW_ATTRIBUTE = 'ADD_NEW_ATTRIBUTE';
